#################################
# DarkBrotherhood Configuration #
#           by iMint            #
#################################

General Settings:
    Use Permissions: false
    Climbable Blocks: [4,5,24,43,44,45,47,48,85,101]
    Multiplier: 2

Item Settings:
    Energy Item: 353
    Lockpick Item: 287
    Lock Item: 77
    Poison Item: 40
    Shuriken Item: 318

Stat Settings:
    Lockpick Success Chance: 25
    Lockpick Failure Damage: 5
    Poison Duration: 5
    Poison Damage: 1
    Shuriken Damage: 2
    # The brightest it can be and still go invisible. 15 always allows invisibility.
    Invisibility Maximum Light Level: 14
    
Leap of Faith Settings:
    Success Chance: 50
    Success Message: You successfully rolled to avoid fall damage!
    Failure Message: You failed to roll, badly injuring yourself!

Energy Settings:
    Maximum Energy: 100
    # How often energy is restored (in seconds)
    Energy Restore Tick: 5
    # How much energy is restored every Restore Tick
    Energy Restore Amount: 5
    # How much energy is restored when eating an Energy item
    Energy Item Restore Amount: 15
    Assassination Energy Usage: 40
    Leap of Faith Energy Usage: 40
    Climbing Energy Usage: 15
    Invisibility Energy Usage: 20
